/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ResidencyManagement;

/**
 *
 * @author Sandesh
 */
public class Issues extends javax.swing.JFrame {

    /**
     * Creates new form Issues
     */
    public Issues() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnShowIssue = new javax.swing.JButton();
        btnDeleteIssue = new javax.swing.JButton();
        btnResolveIssue = new javax.swing.JButton();
        pnlShowIssue = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        lblCreateIssuesDescription1 = new javax.swing.JLabel();
        txtlCreateIssuesLastName1 = new javax.swing.JTextField();
        btnCreateIssuesSubmit1 = new javax.swing.JButton();
        lblCreateIssuesIssueType1 = new javax.swing.JLabel();
        lblCreateIssuesFirstName1 = new javax.swing.JLabel();
        cboxCreateIssuesIssueType1 = new javax.swing.JComboBox<>();
        lblCreateIssuesRoomNumber1 = new javax.swing.JLabel();
        lblCreateIssuesDate1 = new javax.swing.JLabel();
        txtCreateIssuesDate1 = new javax.swing.JTextField();
        lblCreateIssuesApartmentName1 = new javax.swing.JLabel();
        txtCreateIssuesApartmentName1 = new javax.swing.JTextField();
        txtCreateIssuesRoomNumber1 = new javax.swing.JTextField();
        lblCreateIssuesLastName1 = new javax.swing.JLabel();
        txtCreateIssuesDescription1 = new javax.swing.JTextField();
        txtCreateIssuesFirstName1 = new javax.swing.JTextField();
        pnlResolveIssue = new javax.swing.JPanel();
        txtlDeleteUserFirstName = new javax.swing.JTextField();
        lblDeleteUserFirstName = new javax.swing.JLabel();
        btnDeleteUserSubmit = new javax.swing.JButton();
        lblDeleteUserLastName = new javax.swing.JLabel();
        txtDeleteUserLastName = new javax.swing.JTextField();
        lblDeleteUserResidentialId = new javax.swing.JLabel();
        txtDeleteUserResidentialId = new javax.swing.JTextField();
        lblDeleteUserMobileNumber = new javax.swing.JLabel();
        txtDeleteUserMobileNumber = new javax.swing.JTextField();
        pnlDeleteIssue = new javax.swing.JPanel();
        lblDeleteIssueFirstName = new javax.swing.JLabel();
        txtDeleteIssueFirstName = new javax.swing.JTextField();
        lblDeleteIssueLastName = new javax.swing.JLabel();
        txtDeleteIssueLastName = new javax.swing.JTextField();
        btnDeleteIssueSubmit = new javax.swing.JButton();
        lblDeleteIssueDate = new javax.swing.JLabel();
        txtDeleteIssueDate = new javax.swing.JTextField();
        lblDeleteIssueComplainId = new javax.swing.JLabel();
        txtlDeleteIssueComplainId = new javax.swing.JTextField();
        btnCreateIssue = new javax.swing.JButton();
        pnlCreateIssue = new javax.swing.JPanel();
        lblCreateIssuesFirstName = new javax.swing.JLabel();
        txtCreateIssuesFirstName = new javax.swing.JTextField();
        lblCreateIssuesLastName = new javax.swing.JLabel();
        txtlCreateIssuesLastName = new javax.swing.JTextField();
        lblCreateIssuesIssueType = new javax.swing.JLabel();
        cboxCreateIssuesIssueType = new javax.swing.JComboBox<>();
        lblCreateIssuesDate = new javax.swing.JLabel();
        txtCreateIssuesDate = new javax.swing.JTextField();
        lblCreateIssuesApartmentName = new javax.swing.JLabel();
        txtCreateIssuesApartmentName = new javax.swing.JTextField();
        lblCreateIssuesRoomNumber = new javax.swing.JLabel();
        txtCreateIssuesRoomNumber = new javax.swing.JTextField();
        lblCreateIssuesDescription = new javax.swing.JLabel();
        txtCreateIssuesDescription = new javax.swing.JTextField();
        btnCreateIssuesSubmit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnShowIssue.setText("Show Issues");
        btnShowIssue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowIssueActionPerformed(evt);
            }
        });

        btnDeleteIssue.setText("Withdraw Complain");
        btnDeleteIssue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteIssueActionPerformed(evt);
            }
        });

        btnResolveIssue.setText("Resolve Complain");
        btnResolveIssue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResolveIssueActionPerformed(evt);
            }
        });

        pnlShowIssue.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 0)));
        pnlShowIssue.setAutoscrolls(true);
        pnlShowIssue.setPreferredSize(new java.awt.Dimension(1370, 800));

        jButton1.setText("stupid");

        lblCreateIssuesDescription1.setText("Description");

        btnCreateIssuesSubmit1.setText("Submit");
        btnCreateIssuesSubmit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateIssuesSubmit1ActionPerformed(evt);
            }
        });

        lblCreateIssuesIssueType1.setText("Issue Type");

        lblCreateIssuesFirstName1.setText("First Name");

        cboxCreateIssuesIssueType1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Maintenace", "Electricity", "Water Supply", "Ceiling Cracks", "Rent", "Repaint", "Furniture" }));
        cboxCreateIssuesIssueType1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxCreateIssuesIssueType1ActionPerformed(evt);
            }
        });

        lblCreateIssuesRoomNumber1.setText("Room Number");

        lblCreateIssuesDate1.setText("Date");

        lblCreateIssuesApartmentName1.setText("Apartment Name");

        txtCreateIssuesApartmentName1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCreateIssuesApartmentName1ActionPerformed(evt);
            }
        });

        lblCreateIssuesLastName1.setText("Last Name");

        javax.swing.GroupLayout pnlShowIssueLayout = new javax.swing.GroupLayout(pnlShowIssue);
        pnlShowIssue.setLayout(pnlShowIssueLayout);
        pnlShowIssueLayout.setHorizontalGroup(
            pnlShowIssueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlShowIssueLayout.createSequentialGroup()
                .addGroup(pnlShowIssueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlShowIssueLayout.createSequentialGroup()
                        .addGap(488, 488, 488)
                        .addComponent(jButton1))
                    .addGroup(pnlShowIssueLayout.createSequentialGroup()
                        .addGap(397, 397, 397)
                        .addGroup(pnlShowIssueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlShowIssueLayout.createSequentialGroup()
                                .addGroup(pnlShowIssueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblCreateIssuesApartmentName1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblCreateIssuesDate1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblCreateIssuesLastName1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblCreateIssuesIssueType1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblCreateIssuesFirstName1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(pnlShowIssueLayout.createSequentialGroup()
                                        .addComponent(lblCreateIssuesDescription1)
                                        .addGap(122, 122, 122))
                                    .addComponent(lblCreateIssuesRoomNumber1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlShowIssueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtCreateIssuesFirstName1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtlCreateIssuesLastName1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCreateIssuesRoomNumber1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCreateIssuesDate1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCreateIssuesApartmentName1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCreateIssuesDescription1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cboxCreateIssuesIssueType1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(pnlShowIssueLayout.createSequentialGroup()
                                .addGap(109, 109, 109)
                                .addComponent(btnCreateIssuesSubmit1)))))
                .addContainerGap(607, Short.MAX_VALUE))
        );
        pnlShowIssueLayout.setVerticalGroup(
            pnlShowIssueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlShowIssueLayout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addGroup(pnlShowIssueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCreateIssuesFirstName1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCreateIssuesFirstName1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(pnlShowIssueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCreateIssuesLastName1)
                    .addComponent(txtlCreateIssuesLastName1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(pnlShowIssueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCreateIssuesIssueType1)
                    .addComponent(cboxCreateIssuesIssueType1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(pnlShowIssueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCreateIssuesDate1)
                    .addComponent(txtCreateIssuesDate1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(pnlShowIssueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCreateIssuesApartmentName1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCreateIssuesApartmentName1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(pnlShowIssueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCreateIssuesRoomNumber1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCreateIssuesRoomNumber1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(pnlShowIssueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCreateIssuesDescription1)
                    .addComponent(txtCreateIssuesDescription1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addComponent(btnCreateIssuesSubmit1)
                .addGap(474, 474, 474)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlResolveIssue.setPreferredSize(new java.awt.Dimension(1370, 800));

        txtlDeleteUserFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtlDeleteUserFirstNameActionPerformed(evt);
            }
        });

        lblDeleteUserFirstName.setText("First Name");

        btnDeleteUserSubmit.setText("Submit");

        lblDeleteUserLastName.setText("Last  Name");

        lblDeleteUserResidentialId.setText("Residential Id");

        lblDeleteUserMobileNumber.setText("Mobile Number");

        javax.swing.GroupLayout pnlResolveIssueLayout = new javax.swing.GroupLayout(pnlResolveIssue);
        pnlResolveIssue.setLayout(pnlResolveIssueLayout);
        pnlResolveIssueLayout.setHorizontalGroup(
            pnlResolveIssueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlResolveIssueLayout.createSequentialGroup()
                .addGroup(pnlResolveIssueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlResolveIssueLayout.createSequentialGroup()
                        .addGap(475, 475, 475)
                        .addGroup(pnlResolveIssueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlResolveIssueLayout.createSequentialGroup()
                                .addComponent(lblDeleteUserMobileNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDeleteUserMobileNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlResolveIssueLayout.createSequentialGroup()
                                .addComponent(lblDeleteUserResidentialId, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDeleteUserResidentialId, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlResolveIssueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(pnlResolveIssueLayout.createSequentialGroup()
                                    .addComponent(lblDeleteUserLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtDeleteUserLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(pnlResolveIssueLayout.createSequentialGroup()
                                    .addComponent(lblDeleteUserFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtlDeleteUserFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(pnlResolveIssueLayout.createSequentialGroup()
                        .addGap(549, 549, 549)
                        .addComponent(btnDeleteUserSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(591, Short.MAX_VALUE))
        );
        pnlResolveIssueLayout.setVerticalGroup(
            pnlResolveIssueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlResolveIssueLayout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addGroup(pnlResolveIssueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDeleteUserFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtlDeleteUserFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(pnlResolveIssueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDeleteUserLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDeleteUserLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(pnlResolveIssueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDeleteUserResidentialId, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDeleteUserResidentialId, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(pnlResolveIssueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDeleteUserMobileNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDeleteUserMobileNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addComponent(btnDeleteUserSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(339, Short.MAX_VALUE))
        );

        pnlDeleteIssue.setPreferredSize(new java.awt.Dimension(1370, 800));

        lblDeleteIssueFirstName.setText("First Name");

        txtDeleteIssueFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDeleteIssueFirstNameActionPerformed(evt);
            }
        });

        lblDeleteIssueLastName.setText("Last Name");

        btnDeleteIssueSubmit.setText("Submit");

        lblDeleteIssueDate.setText("Date");

        lblDeleteIssueComplainId.setText("Complint Id");

        javax.swing.GroupLayout pnlDeleteIssueLayout = new javax.swing.GroupLayout(pnlDeleteIssue);
        pnlDeleteIssue.setLayout(pnlDeleteIssueLayout);
        pnlDeleteIssueLayout.setHorizontalGroup(
            pnlDeleteIssueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDeleteIssueLayout.createSequentialGroup()
                .addGroup(pnlDeleteIssueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDeleteIssueLayout.createSequentialGroup()
                        .addGap(475, 475, 475)
                        .addGroup(pnlDeleteIssueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlDeleteIssueLayout.createSequentialGroup()
                                .addComponent(lblDeleteIssueFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtDeleteIssueFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlDeleteIssueLayout.createSequentialGroup()
                                .addComponent(lblDeleteIssueDate, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtDeleteIssueDate, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlDeleteIssueLayout.createSequentialGroup()
                                .addComponent(lblDeleteIssueLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtDeleteIssueLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlDeleteIssueLayout.createSequentialGroup()
                                .addComponent(lblDeleteIssueComplainId, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtlDeleteIssueComplainId, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(pnlDeleteIssueLayout.createSequentialGroup()
                        .addGap(562, 562, 562)
                        .addComponent(btnDeleteIssueSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(585, Short.MAX_VALUE))
        );
        pnlDeleteIssueLayout.setVerticalGroup(
            pnlDeleteIssueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDeleteIssueLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(pnlDeleteIssueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDeleteIssueFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDeleteIssueFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(pnlDeleteIssueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDeleteIssueLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDeleteIssueLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(pnlDeleteIssueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDeleteIssueDate, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDeleteIssueDate, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(pnlDeleteIssueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDeleteIssueComplainId, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtlDeleteIssueComplainId, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(btnDeleteIssueSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(426, Short.MAX_VALUE))
        );

        btnCreateIssue.setText("File A Complain");
        btnCreateIssue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateIssueActionPerformed(evt);
            }
        });

        pnlCreateIssue.setPreferredSize(new java.awt.Dimension(1370, 800));

        lblCreateIssuesFirstName.setText("First Name");

        lblCreateIssuesLastName.setText("Last Name");

        lblCreateIssuesIssueType.setText("Issue Type");

        cboxCreateIssuesIssueType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Maintenace", "Electricity", "Water Supply", "Ceiling Cracks", "Rent", "Repaint", "Furniture" }));
        cboxCreateIssuesIssueType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxCreateIssuesIssueTypeActionPerformed(evt);
            }
        });

        lblCreateIssuesDate.setText("Date");

        lblCreateIssuesApartmentName.setText("Apartment Name");

        txtCreateIssuesApartmentName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCreateIssuesApartmentNameActionPerformed(evt);
            }
        });

        lblCreateIssuesRoomNumber.setText("Room Number");

        lblCreateIssuesDescription.setText("Description");

        btnCreateIssuesSubmit.setText("Submit");
        btnCreateIssuesSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateIssuesSubmitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlCreateIssueLayout = new javax.swing.GroupLayout(pnlCreateIssue);
        pnlCreateIssue.setLayout(pnlCreateIssueLayout);
        pnlCreateIssueLayout.setHorizontalGroup(
            pnlCreateIssueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCreateIssueLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(pnlCreateIssueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblCreateIssuesFirstName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblCreateIssuesRoomNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCreateIssuesDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCreateIssuesLastName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblCreateIssuesIssueType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblCreateIssuesDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblCreateIssuesApartmentName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(156, 156, 156)
                .addGroup(pnlCreateIssueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCreateIssuesDate, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtlCreateIssuesLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCreateIssuesFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlCreateIssueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtCreateIssuesDescription, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                        .addComponent(txtCreateIssuesRoomNumber, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                        .addComponent(txtCreateIssuesApartmentName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                    .addComponent(cboxCreateIssuesIssueType, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCreateIssueLayout.createSequentialGroup()
                .addContainerGap(660, Short.MAX_VALUE)
                .addComponent(btnCreateIssuesSubmit)
                .addGap(645, 645, 645))
        );
        pnlCreateIssueLayout.setVerticalGroup(
            pnlCreateIssueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCreateIssueLayout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addGroup(pnlCreateIssueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCreateIssueLayout.createSequentialGroup()
                        .addComponent(lblCreateIssuesFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addGroup(pnlCreateIssueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCreateIssuesLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtlCreateIssuesLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addComponent(lblCreateIssuesIssueType, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(lblCreateIssuesDate, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblCreateIssuesApartmentName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(lblCreateIssuesRoomNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(lblCreateIssuesDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlCreateIssueLayout.createSequentialGroup()
                        .addComponent(txtCreateIssuesFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(101, 101, 101)
                        .addComponent(cboxCreateIssuesIssueType, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtCreateIssuesDate, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtCreateIssuesApartmentName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(txtCreateIssuesRoomNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtCreateIssuesDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(221, 221, 221)
                .addComponent(btnCreateIssuesSubmit)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnShowIssue, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnDeleteIssue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnResolveIssue, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnCreateIssue, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlDeleteIssue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pnlResolveIssue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(pnlCreateIssue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(pnlShowIssue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(pnlShowIssue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(btnCreateIssue, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnShowIssue, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(btnDeleteIssue, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btnResolveIssue, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(pnlCreateIssue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(491, 491, 491)
                        .addComponent(pnlResolveIssue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pnlDeleteIssue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnShowIssueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowIssueActionPerformed
        // TODO add your handling code here:
        
        pnlDeleteIssue.setVisible(false);
        pnlResolveIssue.setVisible(false);
        pnlCreateIssue.setVisible(false);
        pnlShowIssue.setVisible(true);
    }//GEN-LAST:event_btnShowIssueActionPerformed

    private void btnDeleteIssueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteIssueActionPerformed
        // TODO add your handling code here:
       
        pnlCreateIssue.setVisible(false);
        pnlShowIssue.setVisible(false);
        pnlResolveIssue.setVisible(false);
        pnlDeleteIssue.setVisible(true);
    }//GEN-LAST:event_btnDeleteIssueActionPerformed

    private void btnResolveIssueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResolveIssueActionPerformed
        // TODO add your handling code here:
        pnlCreateIssue.setVisible(false);
        pnlShowIssue.setVisible(false);
        pnlDeleteIssue.setVisible(false);
        pnlResolveIssue.setVisible(true);
    }//GEN-LAST:event_btnResolveIssueActionPerformed

    private void txtlDeleteUserFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtlDeleteUserFirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtlDeleteUserFirstNameActionPerformed

    private void btnCreateIssueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateIssueActionPerformed
        // TODO add your handling code here:
        pnlShowIssue.setVisible(false);
        pnlDeleteIssue.setVisible(false);
        pnlResolveIssue.setVisible(false);
        pnlCreateIssue.setVisible(true);
    }//GEN-LAST:event_btnCreateIssueActionPerformed

    private void btnCreateIssuesSubmit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateIssuesSubmit1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCreateIssuesSubmit1ActionPerformed

    private void cboxCreateIssuesIssueType1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxCreateIssuesIssueType1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboxCreateIssuesIssueType1ActionPerformed

    private void txtCreateIssuesApartmentName1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCreateIssuesApartmentName1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCreateIssuesApartmentName1ActionPerformed

    private void txtDeleteIssueFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDeleteIssueFirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDeleteIssueFirstNameActionPerformed

    private void btnCreateIssuesSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateIssuesSubmitActionPerformed
        // TODO add your handling code here:
        //JOptionPane.showMessageDialog(User.this, "Data accepted");
    }//GEN-LAST:event_btnCreateIssuesSubmitActionPerformed

    private void txtCreateIssuesApartmentNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCreateIssuesApartmentNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCreateIssuesApartmentNameActionPerformed

    private void cboxCreateIssuesIssueTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxCreateIssuesIssueTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboxCreateIssuesIssueTypeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Issues.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Issues.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Issues.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Issues.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Issues().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateIssue;
    private javax.swing.JButton btnCreateIssuesSubmit;
    private javax.swing.JButton btnCreateIssuesSubmit1;
    private javax.swing.JButton btnCreateIssuesSubmit2;
    private javax.swing.JButton btnDeleteIssue;
    private javax.swing.JButton btnDeleteIssueSubmit;
    private javax.swing.JButton btnDeleteUserSubmit;
    private javax.swing.JButton btnResolveIssue;
    private javax.swing.JButton btnShowIssue;
    private javax.swing.JComboBox<String> cboxCreateIssuesIssueType;
    private javax.swing.JComboBox<String> cboxCreateIssuesIssueType1;
    private javax.swing.JComboBox<String> cboxCreateIssuesIssueType2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel lblCreateIssuesApartmentName;
    private javax.swing.JLabel lblCreateIssuesApartmentName1;
    private javax.swing.JLabel lblCreateIssuesApartmentName2;
    private javax.swing.JLabel lblCreateIssuesDate;
    private javax.swing.JLabel lblCreateIssuesDate1;
    private javax.swing.JLabel lblCreateIssuesDate2;
    private javax.swing.JLabel lblCreateIssuesDescription;
    private javax.swing.JLabel lblCreateIssuesDescription1;
    private javax.swing.JLabel lblCreateIssuesDescription2;
    private javax.swing.JLabel lblCreateIssuesFirstName;
    private javax.swing.JLabel lblCreateIssuesFirstName1;
    private javax.swing.JLabel lblCreateIssuesFirstName2;
    private javax.swing.JLabel lblCreateIssuesIssueType;
    private javax.swing.JLabel lblCreateIssuesIssueType1;
    private javax.swing.JLabel lblCreateIssuesIssueType2;
    private javax.swing.JLabel lblCreateIssuesLastName;
    private javax.swing.JLabel lblCreateIssuesLastName1;
    private javax.swing.JLabel lblCreateIssuesLastName2;
    private javax.swing.JLabel lblCreateIssuesRoomNumber;
    private javax.swing.JLabel lblCreateIssuesRoomNumber1;
    private javax.swing.JLabel lblCreateIssuesRoomNumber2;
    private javax.swing.JLabel lblDeleteIssueComplainId;
    private javax.swing.JLabel lblDeleteIssueDate;
    private javax.swing.JLabel lblDeleteIssueFirstName;
    private javax.swing.JLabel lblDeleteIssueLastName;
    private javax.swing.JLabel lblDeleteUserFirstName;
    private javax.swing.JLabel lblDeleteUserLastName;
    private javax.swing.JLabel lblDeleteUserMobileNumber;
    private javax.swing.JLabel lblDeleteUserResidentialId;
    private javax.swing.JPanel pnlCreateIssue;
    private javax.swing.JPanel pnlDeleteIssue;
    private javax.swing.JPanel pnlIssues1;
    private javax.swing.JPanel pnlResolveIssue;
    private javax.swing.JPanel pnlShowIssue;
    private javax.swing.JTextField txtCreateIssuesApartmentName;
    private javax.swing.JTextField txtCreateIssuesApartmentName1;
    private javax.swing.JTextField txtCreateIssuesApartmentName2;
    private javax.swing.JTextField txtCreateIssuesDate;
    private javax.swing.JTextField txtCreateIssuesDate1;
    private javax.swing.JTextField txtCreateIssuesDate2;
    private javax.swing.JTextField txtCreateIssuesDescription;
    private javax.swing.JTextField txtCreateIssuesDescription1;
    private javax.swing.JTextField txtCreateIssuesDescription2;
    private javax.swing.JTextField txtCreateIssuesFirstName;
    private javax.swing.JTextField txtCreateIssuesFirstName1;
    private javax.swing.JTextField txtCreateIssuesFirstName2;
    private javax.swing.JTextField txtCreateIssuesRoomNumber;
    private javax.swing.JTextField txtCreateIssuesRoomNumber1;
    private javax.swing.JTextField txtCreateIssuesRoomNumber2;
    private javax.swing.JTextField txtDeleteIssueDate;
    private javax.swing.JTextField txtDeleteIssueFirstName;
    private javax.swing.JTextField txtDeleteIssueLastName;
    private javax.swing.JTextField txtDeleteUserLastName;
    private javax.swing.JTextField txtDeleteUserMobileNumber;
    private javax.swing.JTextField txtDeleteUserResidentialId;
    private javax.swing.JTextField txtlCreateIssuesLastName;
    private javax.swing.JTextField txtlCreateIssuesLastName1;
    private javax.swing.JTextField txtlCreateIssuesLastName2;
    private javax.swing.JTextField txtlDeleteIssueComplainId;
    private javax.swing.JTextField txtlDeleteUserFirstName;
    // End of variables declaration//GEN-END:variables
}
