/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ResidencyManagement;

/**
 *
 * @author Sandesh
 */
public class temp extends javax.swing.JFrame {

    /**
     * Creates new form temp
     */
    public temp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtIssuesFirstName = new javax.swing.JTextField();
        lblIssuesLastName = new javax.swing.JLabel();
        txtIssuesLastName = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        lblIssuesIssueType = new javax.swing.JLabel();
        lbIssuesDate = new javax.swing.JLabel();
        txtIssuesAddress = new javax.swing.JTextField();
        lblIssuesApartmentName = new javax.swing.JLabel();
        txtIssuesApartmentName = new javax.swing.JTextField();
        lblIssuesRoomNumber = new javax.swing.JLabel();
        txtIssuesRoomNumber = new javax.swing.JTextField();
        txtIssuesDesccription = new javax.swing.JTextField();
        lblIssuesDescription = new javax.swing.JLabel();
        btnSubmitUser = new javax.swing.JButton();
        lbltempFirstName = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1370, 800));

        lblIssuesLastName.setText("Last Name");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Maintenace", "Electricity", "Water Supply", "Ceiling Cracks", "Rent", "Repaint", "Furniture" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        lblIssuesIssueType.setText("Issue Type");

        lbIssuesDate.setText("Date");

        lblIssuesApartmentName.setText("Apartment Name");

        txtIssuesApartmentName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIssuesApartmentNameActionPerformed(evt);
            }
        });

        lblIssuesRoomNumber.setText("Room Number");

        lblIssuesDescription.setText("Description");

        btnSubmitUser.setText("Submit");
        btnSubmitUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitUserActionPerformed(evt);
            }
        });

        lbltempFirstName.setText("First Name");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lbltempFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1196, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblIssuesRoomNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblIssuesApartmentName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbIssuesDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblIssuesLastName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblIssuesIssueType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblIssuesDescription, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGap(122, 122, 122)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtIssuesFirstName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                                .addComponent(txtIssuesLastName, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtIssuesRoomNumber, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtIssuesAddress, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtIssuesApartmentName, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtIssuesDesccription, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(109, 109, 109)
                            .addComponent(btnSubmitUser)))
                    .addContainerGap(987, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbltempFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(575, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(txtIssuesFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(35, 35, 35)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblIssuesLastName)
                        .addComponent(txtIssuesLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(40, 40, 40)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblIssuesIssueType)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(32, 32, 32)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbIssuesDate)
                        .addComponent(txtIssuesAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(36, 36, 36)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblIssuesApartmentName)
                        .addComponent(txtIssuesApartmentName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(36, 36, 36)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblIssuesRoomNumber)
                        .addComponent(txtIssuesRoomNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(30, 30, 30)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblIssuesDescription)
                        .addComponent(txtIssuesDesccription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(54, 54, 54)
                    .addComponent(btnSubmitUser)
                    .addContainerGap(197, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void txtIssuesApartmentNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIssuesApartmentNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIssuesApartmentNameActionPerformed

    private void btnSubmitUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitUserActionPerformed
        // TODO add your handling code here:
        new temp().setVisible(true);
        this.dispose();
        //JOptionPane.showMessageDialog(User.this, "Data accepted");
    }//GEN-LAST:event_btnSubmitUserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(temp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(temp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(temp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(temp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new temp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSubmitUser;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel lbIssuesDate;
    private javax.swing.JLabel lblIssuesApartmentName;
    private javax.swing.JLabel lblIssuesDescription;
    private javax.swing.JLabel lblIssuesIssueType;
    private javax.swing.JLabel lblIssuesLastName;
    private javax.swing.JLabel lblIssuesRoomNumber;
    private javax.swing.JLabel lbltempFirstName;
    private javax.swing.JTextField txtIssuesAddress;
    private javax.swing.JTextField txtIssuesApartmentName;
    private javax.swing.JTextField txtIssuesDesccription;
    private javax.swing.JTextField txtIssuesFirstName;
    private javax.swing.JTextField txtIssuesLastName;
    private javax.swing.JTextField txtIssuesRoomNumber;
    // End of variables declaration//GEN-END:variables
}
