/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com;

//import com.mongodb.client.MongoDatabase; 

import javax.swing.JOptionPane;

//import com.mongodb.MongoClient; 
//import com.mongodb.MongoCredential;  
//import javax.swing.JOptionPane;

/**
 *
 * @author Sandesh
 */
public class User extends javax.swing.JFrame {

    /**
     * Creates new form User
     */
    public User() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCreateUser = new javax.swing.JButton();
        btnIssues = new javax.swing.JButton();
        pnlIssues = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        pnlCreateUser = new javax.swing.JLayeredPane();
        lblFirstName = new javax.swing.JLabel();
        lblLastName = new javax.swing.JLabel();
        lblGender = new javax.swing.JLabel();
        lblAdress = new javax.swing.JLabel();
        lblCityName = new javax.swing.JLabel();
        lblProfession = new javax.swing.JLabel();
        lblApartmentName = new javax.swing.JLabel();
        lblRoomNumber = new javax.swing.JLabel();
        lblMobileNumber = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblMembership = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        txtLastName = new javax.swing.JTextField();
        txtRoomNumber = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        txtCityName = new javax.swing.JTextField();
        txtProfession = new javax.swing.JTextField();
        txtApartmentName = new javax.swing.JTextField();
        txtMobileNumber = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        ckboxYes = new javax.swing.JCheckBox();
        btnSubmitUser = new javax.swing.JButton();
        dboxGender = new javax.swing.JComboBox<>();
        btnUpdateUser = new javax.swing.JButton();
        btnDeleteUser = new javax.swing.JButton();
        pnlUpdateUser = new javax.swing.JPanel();
        lblUpdateUserFirstName = new javax.swing.JLabel();
        txtUpdateUserFirstName = new javax.swing.JTextField();
        lblUpdateUserEnterDetails = new javax.swing.JLabel();
        txtUpdateUserEnterDetails = new javax.swing.JTextField();
        btnUpdateUserSubmit = new javax.swing.JButton();
        cboxUpdateUserEnterDetails = new javax.swing.JComboBox<>();
        pnlDeleteUser = new javax.swing.JPanel();
        txtlDeleteUserFirstName = new javax.swing.JTextField();
        lblDeleteUserFirstName = new javax.swing.JLabel();
        btnDeleteUserSubmit = new javax.swing.JButton();
        lblDeleteUserLastName = new javax.swing.JLabel();
        txtDeleteUserLastName = new javax.swing.JTextField();
        lblDeleteUserResidentialId = new javax.swing.JLabel();
        txtDeleteUserResidentialId = new javax.swing.JTextField();
        lblDeleteUserMobileNumber = new javax.swing.JLabel();
        txtDeleteUserMobileNumber = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1550, 870));

        btnCreateUser.setText("Create User");
        btnCreateUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateUserActionPerformed(evt);
            }
        });

        btnIssues.setText("Show Users");
        btnIssues.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIssuesActionPerformed(evt);
            }
        });

        pnlIssues.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 0)));
        pnlIssues.setAutoscrolls(true);
        pnlIssues.setPreferredSize(new java.awt.Dimension(1370, 800));

        jButton1.setText("stupid");

        jLabel1.setText("Hiiiiiiiiii");

        javax.swing.GroupLayout pnlIssuesLayout = new javax.swing.GroupLayout(pnlIssues);
        pnlIssues.setLayout(pnlIssuesLayout);
        pnlIssuesLayout.setHorizontalGroup(
            pnlIssuesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlIssuesLayout.createSequentialGroup()
                .addGroup(pnlIssuesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlIssuesLayout.createSequentialGroup()
                        .addGap(488, 488, 488)
                        .addComponent(jButton1))
                    .addGroup(pnlIssuesLayout.createSequentialGroup()
                        .addGap(437, 437, 437)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(738, Short.MAX_VALUE))
        );
        pnlIssuesLayout.setVerticalGroup(
            pnlIssuesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlIssuesLayout.createSequentialGroup()
                .addGap(295, 295, 295)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(585, 585, 585)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlCreateUser.setPreferredSize(new java.awt.Dimension(1370, 800));

        lblFirstName.setText("First Name");

        lblLastName.setText("Last Name");

        lblGender.setText("Gender");

        lblAdress.setText("Address");

        lblCityName.setText("City Name");

        lblProfession.setText("Profession");

        lblApartmentName.setText("Apartment Name");

        lblRoomNumber.setText("Room Number");

        lblMobileNumber.setText("Mobile Number");

        lblEmail.setText("Email");

        lblMembership.setText("Membership");

        txtApartmentName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApartmentNameActionPerformed(evt);
            }
        });

        ckboxYes.setText("Yes");

        btnSubmitUser.setText("Submit");
        btnSubmitUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitUserActionPerformed(evt);
            }
        });

        dboxGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Others" }));

        pnlCreateUser.setLayer(lblFirstName, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pnlCreateUser.setLayer(lblLastName, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pnlCreateUser.setLayer(lblGender, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pnlCreateUser.setLayer(lblAdress, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pnlCreateUser.setLayer(lblCityName, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pnlCreateUser.setLayer(lblProfession, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pnlCreateUser.setLayer(lblApartmentName, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pnlCreateUser.setLayer(lblRoomNumber, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pnlCreateUser.setLayer(lblMobileNumber, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pnlCreateUser.setLayer(lblEmail, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pnlCreateUser.setLayer(lblMembership, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pnlCreateUser.setLayer(txtFirstName, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pnlCreateUser.setLayer(txtLastName, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pnlCreateUser.setLayer(txtRoomNumber, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pnlCreateUser.setLayer(txtAddress, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pnlCreateUser.setLayer(txtCityName, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pnlCreateUser.setLayer(txtProfession, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pnlCreateUser.setLayer(txtApartmentName, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pnlCreateUser.setLayer(txtMobileNumber, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pnlCreateUser.setLayer(txtEmail, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pnlCreateUser.setLayer(ckboxYes, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pnlCreateUser.setLayer(btnSubmitUser, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pnlCreateUser.setLayer(dboxGender, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout pnlCreateUserLayout = new javax.swing.GroupLayout(pnlCreateUser);
        pnlCreateUser.setLayout(pnlCreateUserLayout);
        pnlCreateUserLayout.setHorizontalGroup(
            pnlCreateUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCreateUserLayout.createSequentialGroup()
                .addGroup(pnlCreateUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCreateUserLayout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addGroup(pnlCreateUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblMembership, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblMobileNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblRoomNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblApartmentName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblProfession, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblAdress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblFirstName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblLastName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblGender, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblCityName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(115, 115, 115)
                        .addGroup(pnlCreateUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ckboxYes, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlCreateUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(dboxGender, javax.swing.GroupLayout.Alignment.LEADING, 0, 150, Short.MAX_VALUE)
                                .addComponent(txtEmail, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtMobileNumber, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtFirstName, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtLastName, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtRoomNumber, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtAddress, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtCityName, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtProfession, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtApartmentName, javax.swing.GroupLayout.Alignment.LEADING))))
                    .addGroup(pnlCreateUserLayout.createSequentialGroup()
                        .addGap(244, 244, 244)
                        .addComponent(btnSubmitUser)))
                .addContainerGap(914, Short.MAX_VALUE))
        );
        pnlCreateUserLayout.setVerticalGroup(
            pnlCreateUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCreateUserLayout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addGroup(pnlCreateUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlCreateUserLayout.createSequentialGroup()
                        .addGroup(pnlCreateUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFirstName)
                            .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(pnlCreateUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblLastName)
                            .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(pnlCreateUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblGender)
                            .addComponent(dboxGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(pnlCreateUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCreateUserLayout.createSequentialGroup()
                                .addGroup(pnlCreateUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCreateUserLayout.createSequentialGroup()
                                        .addGroup(pnlCreateUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(lblAdress)
                                            .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(35, 35, 35)
                                        .addComponent(lblCityName))
                                    .addComponent(txtCityName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(35, 35, 35)
                                .addComponent(lblProfession))
                            .addComponent(txtProfession, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addComponent(lblApartmentName))
                    .addComponent(txtApartmentName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(pnlCreateUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRoomNumber)
                    .addComponent(txtRoomNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(pnlCreateUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMobileNumber)
                    .addComponent(txtMobileNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(pnlCreateUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmail)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(pnlCreateUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMembership)
                    .addComponent(ckboxYes))
                .addGap(35, 35, 35)
                .addComponent(btnSubmitUser)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        btnUpdateUser.setText("Update User");
        btnUpdateUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateUserActionPerformed(evt);
            }
        });

        btnDeleteUser.setText("Delete User");
        btnDeleteUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteUserActionPerformed(evt);
            }
        });

        pnlUpdateUser.setPreferredSize(new java.awt.Dimension(1370, 800));

        lblUpdateUserFirstName.setText("Registrstion Id");

        txtUpdateUserFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUpdateUserFirstNameActionPerformed(evt);
            }
        });

        lblUpdateUserEnterDetails.setText("Enter Details");

        btnUpdateUserSubmit.setText("Submit");

        cboxUpdateUserEnterDetails.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Full Name", "Registration Id", "Mobile No", "Address", "Age" }));

        javax.swing.GroupLayout pnlUpdateUserLayout = new javax.swing.GroupLayout(pnlUpdateUser);
        pnlUpdateUser.setLayout(pnlUpdateUserLayout);
        pnlUpdateUserLayout.setHorizontalGroup(
            pnlUpdateUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUpdateUserLayout.createSequentialGroup()
                .addGroup(pnlUpdateUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlUpdateUserLayout.createSequentialGroup()
                        .addGap(549, 549, 549)
                        .addComponent(btnUpdateUserSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlUpdateUserLayout.createSequentialGroup()
                        .addGap(582, 582, 582)
                        .addComponent(cboxUpdateUserEnterDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlUpdateUserLayout.createSequentialGroup()
                        .addGap(475, 475, 475)
                        .addGroup(pnlUpdateUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlUpdateUserLayout.createSequentialGroup()
                                .addComponent(lblUpdateUserFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtUpdateUserFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlUpdateUserLayout.createSequentialGroup()
                                .addComponent(lblUpdateUserEnterDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtUpdateUserEnterDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(585, Short.MAX_VALUE))
        );
        pnlUpdateUserLayout.setVerticalGroup(
            pnlUpdateUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUpdateUserLayout.createSequentialGroup()
                .addGap(196, 196, 196)
                .addGroup(pnlUpdateUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUpdateUserFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUpdateUserFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(cboxUpdateUserEnterDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addGroup(pnlUpdateUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUpdateUserEnterDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUpdateUserEnterDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addComponent(btnUpdateUserSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(339, Short.MAX_VALUE))
        );

        pnlDeleteUser.setPreferredSize(new java.awt.Dimension(1370, 800));

        txtlDeleteUserFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtlDeleteUserFirstNameActionPerformed(evt);
            }
        });

        lblDeleteUserFirstName.setText("First Name");

        btnDeleteUserSubmit.setText("Submit");

        lblDeleteUserLastName.setText("Last  Name");

        lblDeleteUserResidentialId.setText("Residential Id");

        lblDeleteUserMobileNumber.setText("Mobile Number");

        javax.swing.GroupLayout pnlDeleteUserLayout = new javax.swing.GroupLayout(pnlDeleteUser);
        pnlDeleteUser.setLayout(pnlDeleteUserLayout);
        pnlDeleteUserLayout.setHorizontalGroup(
            pnlDeleteUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDeleteUserLayout.createSequentialGroup()
                .addGroup(pnlDeleteUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDeleteUserLayout.createSequentialGroup()
                        .addGap(475, 475, 475)
                        .addGroup(pnlDeleteUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlDeleteUserLayout.createSequentialGroup()
                                .addComponent(lblDeleteUserMobileNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDeleteUserMobileNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlDeleteUserLayout.createSequentialGroup()
                                .addComponent(lblDeleteUserResidentialId, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDeleteUserResidentialId, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlDeleteUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(pnlDeleteUserLayout.createSequentialGroup()
                                    .addComponent(lblDeleteUserLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtDeleteUserLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(pnlDeleteUserLayout.createSequentialGroup()
                                    .addComponent(lblDeleteUserFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtlDeleteUserFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(pnlDeleteUserLayout.createSequentialGroup()
                        .addGap(549, 549, 549)
                        .addComponent(btnDeleteUserSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(591, Short.MAX_VALUE))
        );
        pnlDeleteUserLayout.setVerticalGroup(
            pnlDeleteUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDeleteUserLayout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addGroup(pnlDeleteUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDeleteUserFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtlDeleteUserFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(pnlDeleteUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDeleteUserLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDeleteUserLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(pnlDeleteUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDeleteUserResidentialId, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDeleteUserResidentialId, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(pnlDeleteUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDeleteUserMobileNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDeleteUserMobileNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addComponent(btnDeleteUserSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(339, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnCreateUser, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                        .addComponent(btnIssues, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnUpdateUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDeleteUser, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlUpdateUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pnlDeleteUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlCreateUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlIssues, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCreateUser, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(btnIssues, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(btnUpdateUser, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(btnDeleteUser, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pnlIssues, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlCreateUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlUpdateUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlDeleteUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateUserActionPerformed
        // TODO add your handling code here:
        pnlIssues.setVisible(false);
        pnlUpdateUser.setVisible(false);
        pnlDeleteUser.setVisible(false);
        pnlCreateUser.setVisible(true);
       
    }//GEN-LAST:event_btnCreateUserActionPerformed

    private void btnIssuesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIssuesActionPerformed
        // TODO add your handling code here:
        pnlCreateUser.setVisible(false);
        pnlUpdateUser.setVisible(false);
        pnlDeleteUser.setVisible(false);
        pnlIssues.setVisible(true);
    }//GEN-LAST:event_btnIssuesActionPerformed

    private void txtApartmentNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApartmentNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApartmentNameActionPerformed

    private void btnSubmitUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitUserActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(User.this, "Data accepted");
    }//GEN-LAST:event_btnSubmitUserActionPerformed

    private void btnUpdateUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateUserActionPerformed
        // TODO add your handling code here:
        pnlCreateUser.setVisible(false);
        pnlDeleteUser.setVisible(false);
        pnlIssues.setVisible(false);
        pnlUpdateUser.setVisible(true);
    }//GEN-LAST:event_btnUpdateUserActionPerformed

    private void btnDeleteUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteUserActionPerformed
        // TODO add your handling code here:
        pnlCreateUser.setVisible(false);
        pnlUpdateUser.setVisible(false);
        pnlIssues.setVisible(false);
        pnlDeleteUser.setVisible(true);
    }//GEN-LAST:event_btnDeleteUserActionPerformed

    private void txtlDeleteUserFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtlDeleteUserFirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtlDeleteUserFirstNameActionPerformed

    private void txtUpdateUserFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUpdateUserFirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUpdateUserFirstNameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new User().setVisible(true);
        });
        
         //MongoClient mongo = new MongoClient( "localhost" , 27017 ); 
   
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateUser;
    private javax.swing.JButton btnDeleteUser;
    private javax.swing.JButton btnDeleteUserSubmit;
    private javax.swing.JButton btnIssues;
    private javax.swing.JButton btnSubmitUser;
    private javax.swing.JButton btnUpdateUser;
    private javax.swing.JButton btnUpdateUserSubmit;
    private javax.swing.JComboBox<String> cboxUpdateUserEnterDetails;
    private javax.swing.JCheckBox ckboxYes;
    private javax.swing.JComboBox<String> dboxGender;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblAdress;
    private javax.swing.JLabel lblApartmentName;
    private javax.swing.JLabel lblCityName;
    private javax.swing.JLabel lblDeleteUserFirstName;
    private javax.swing.JLabel lblDeleteUserLastName;
    private javax.swing.JLabel lblDeleteUserMobileNumber;
    private javax.swing.JLabel lblDeleteUserResidentialId;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblMembership;
    private javax.swing.JLabel lblMobileNumber;
    private javax.swing.JLabel lblProfession;
    private javax.swing.JLabel lblRoomNumber;
    private javax.swing.JLabel lblUpdateUserEnterDetails;
    private javax.swing.JLabel lblUpdateUserFirstName;
    private javax.swing.JLayeredPane pnlCreateUser;
    private javax.swing.JPanel pnlDeleteUser;
    private javax.swing.JPanel pnlIssues;
    private javax.swing.JPanel pnlUpdateUser;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtApartmentName;
    private javax.swing.JTextField txtCityName;
    private javax.swing.JTextField txtDeleteUserLastName;
    private javax.swing.JTextField txtDeleteUserMobileNumber;
    private javax.swing.JTextField txtDeleteUserResidentialId;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtMobileNumber;
    private javax.swing.JTextField txtProfession;
    private javax.swing.JTextField txtRoomNumber;
    private javax.swing.JTextField txtUpdateUserEnterDetails;
    private javax.swing.JTextField txtUpdateUserFirstName;
    private javax.swing.JTextField txtlDeleteUserFirstName;
    // End of variables declaration//GEN-END:variables
}
